### **Obtener información de la API generada por el sitio `mindicador.cl/api`, normalizarla en un Dataframe y exportarla a un archivo CSV**

Utilizamos la siguiente API:

https://mindicador.cl/api/

### **`Prueba 1`**

#### **Conexión a la API**

In [1]:
import requests
import json
import pandas as pd
from pprint import pprint

response = requests.get("https://mindicador.cl/api/")
print(response.status_code) # 200 ==> Quiere decir que la conexión es satisfactoria

200

#### **Extraer información en el tipo `string`**

In [2]:
print(response.text)
print(type(response.text)) # <class 'str'>

{"version":"1.7.0","autor":"mindicador.cl","fecha":"2024-04-01T18:00:00.000Z","uf":{"codigo":"uf","nombre":"Unidad de fomento (UF)","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":37100.68},"ivp":{"codigo":"ivp","nombre":"Indice de valor promedio (IVP)","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":38457.59},"dolar":{"codigo":"dolar","nombre":"Dólar observado","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":981.71},"dolar_intercambio":{"codigo":"dolar_intercambio","nombre":"Dólar acuerdo","unidad_medida":"Pesos","fecha":"2014-11-13T03:00:00.000Z","valor":758.87},"euro":{"codigo":"euro","nombre":"Euro","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":1060.05},"ipc":{"codigo":"ipc","nombre":"Indice de Precios al Consumidor (IPC)","unidad_medida":"Porcentaje","fecha":"2024-02-01T03:00:00.000Z","valor":0.6},"utm":{"codigo":"utm","nombre":"Unidad Tributaria Mensual (UTM)","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":65182},"imacec":{"codigo":"imacec","nombre":"Imacec","unidad_medida":"Porcentaje","fecha":"2024-02-01T03:00:00.000Z","valor":4.5},"tpm":{"codigo":"tpm","nombre":"Tasa Política Monetaria (TPM)","unidad_medida":"Porcentaje","fecha":"2024-04-01T03:00:00.000Z","valor":7.25},"libra_cobre":{"codigo":"libra_cobre","nombre":"Libra de Cobre","unidad_medida":"Dólar","fecha":"2024-04-01T03:00:00.000Z","valor":3.97},"tasa_desempleo":{"codigo":"tasa_desempleo","nombre":"Tasa de desempleo","unidad_medida":"Porcentaje","fecha":"2024-02-01T03:00:00.000Z","valor":8.5},"bitcoin":{"codigo":"bitcoin","nombre":"Bitcoin","unidad_medida":"Dólar","fecha":"2024-02-01T03:00:00.000Z","valor":43061.16}}
<class 'str'>

#### **Extraer información en el tipo `diccionario`**

In [3]:
pprint(response.json())
print(type(response.json())) # <class 'dict'>

{'autor': 'mindicador.cl',
 'bitcoin': {'codigo': 'bitcoin',
             'fecha': '2024-02-01T03:00:00.000Z',
             'nombre': 'Bitcoin',
             'unidad_medida': 'Dólar',
             'valor': 43061.16},
 'dolar': {'codigo': 'dolar',
           'fecha': '2024-04-01T03:00:00.000Z',
           'nombre': 'Dólar observado',
           'unidad_medida': 'Pesos',
           'valor': 981.71},
 'dolar_intercambio': {'codigo': 'dolar_intercambio',
                       'fecha': '2014-11-13T03:00:00.000Z',
                       'nombre': 'Dólar acuerdo',
                       'unidad_medida': 'Pesos',
                       'valor': 758.87},
 'euro': {'codigo': 'euro',
          'fecha': '2024-04-01T03:00:00.000Z',
          'nombre': 'Euro',
          'unidad_medida': 'Pesos',
          'valor': 1060.05},
 'fecha': '2024-04-01T18:00:00.000Z',
 'imacec': {'codigo': 'imacec',
            'fecha': '2024-02-01T03:00:00.000Z',
            'nombre': 'Imacec',
            'unidad_medida': 'Porcentaje',
            'valor': 4.5},
 'ipc': {'codigo': 'ipc',
         'fecha': '2024-02-01T03:00:00.000Z',
         'nombre': 'Indice de Precios al Consumidor (IPC)',
         'unidad_medida': 'Porcentaje',
         'valor': 0.6},
 'ivp': {'codigo': 'ivp',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Indice de valor promedio (IVP)',
         'unidad_medida': 'Pesos',
         'valor': 38457.59},
 'libra_cobre': {'codigo': 'libra_cobre',
                 'fecha': '2024-04-01T03:00:00.000Z',
                 'nombre': 'Libra de Cobre',
                 'unidad_medida': 'Dólar',
                 'valor': 3.97},
 'tasa_desempleo': {'codigo': 'tasa_desempleo',
                    'fecha': '2024-02-01T03:00:00.000Z',
                    'nombre': 'Tasa de desempleo',
                    'unidad_medida': 'Porcentaje',
                    'valor': 8.5},
 'tpm': {'codigo': 'tpm',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Tasa Política Monetaria (TPM)',
         'unidad_medida': 'Porcentaje',
         'valor': 7.25},
 'uf': {'codigo': 'uf',
        'fecha': '2024-04-01T03:00:00.000Z',
        'nombre': 'Unidad de fomento (UF)',
        'unidad_medida': 'Pesos',
        'valor': 37100.68},
 'utm': {'codigo': 'utm',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Unidad Tributaria Mensual (UTM)',
         'unidad_medida': 'Pesos',
         'valor': 65182},
 'version': '1.7.0'}
<class 'dict'>

In [4]:
respuesta = json.loads(response.text)
pprint(respuesta)
print(type(respuesta)) # <class 'dict'>

{'autor': 'mindicador.cl',
 'bitcoin': {'codigo': 'bitcoin',
             'fecha': '2024-02-01T03:00:00.000Z',
             'nombre': 'Bitcoin',
             'unidad_medida': 'Dólar',
             'valor': 43061.16},
 'dolar': {'codigo': 'dolar',
           'fecha': '2024-04-01T03:00:00.000Z',
           'nombre': 'Dólar observado',
           'unidad_medida': 'Pesos',
           'valor': 981.71},
 'dolar_intercambio': {'codigo': 'dolar_intercambio',
                       'fecha': '2014-11-13T03:00:00.000Z',
                       'nombre': 'Dólar acuerdo',
                       'unidad_medida': 'Pesos',
                       'valor': 758.87},
 'euro': {'codigo': 'euro',
          'fecha': '2024-04-01T03:00:00.000Z',
          'nombre': 'Euro',
          'unidad_medida': 'Pesos',
          'valor': 1060.05},
 'fecha': '2024-04-01T18:00:00.000Z',
 'imacec': {'codigo': 'imacec',
            'fecha': '2024-02-01T03:00:00.000Z',
            'nombre': 'Imacec',
            'unidad_medida': 'Porcentaje',
            'valor': 4.5},
 'ipc': {'codigo': 'ipc',
         'fecha': '2024-02-01T03:00:00.000Z',
         'nombre': 'Indice de Precios al Consumidor (IPC)',
         'unidad_medida': 'Porcentaje',
         'valor': 0.6},
 'ivp': {'codigo': 'ivp',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Indice de valor promedio (IVP)',
         'unidad_medida': 'Pesos',
         'valor': 38457.59},
 'libra_cobre': {'codigo': 'libra_cobre',
                 'fecha': '2024-04-01T03:00:00.000Z',
                 'nombre': 'Libra de Cobre',
                 'unidad_medida': 'Dólar',
                 'valor': 3.97},
 'tasa_desempleo': {'codigo': 'tasa_desempleo',
                    'fecha': '2024-02-01T03:00:00.000Z',
                    'nombre': 'Tasa de desempleo',
                    'unidad_medida': 'Porcentaje',
                    'valor': 8.5},
 'tpm': {'codigo': 'tpm',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Tasa Política Monetaria (TPM)',
         'unidad_medida': 'Porcentaje',
         'valor': 7.25},
 'uf': {'codigo': 'uf',
        'fecha': '2024-04-01T03:00:00.000Z',
        'nombre': 'Unidad de fomento (UF)',
        'unidad_medida': 'Pesos',
        'valor': 37100.68},
 'utm': {'codigo': 'utm',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Unidad Tributaria Mensual (UTM)',
         'unidad_medida': 'Pesos',
         'valor': 65182},
 'version': '1.7.0'}
<class 'dict'>

#### **Normalizar data en un Dataframe**

Esta no es la mejor manera de normalizar un json, dado que nos entrega una fila y 63 columnas:

In [5]:
df = pd.json_normalize(respuesta)
df

,version,autor,fecha,uf.codigo,uf.nombre,uf.unidad_medida,uf.fecha,uf.valor,ivp.codigo,ivp.nombre,...,tasa_desempleo.codigo,tasa_desempleo.nombre,tasa_desempleo.unidad_medida,tasa_desempleo.fecha,tasa_desempleo.valor,bitcoin.codigo,bitcoin.nombre,bitcoin.unidad_medida,bitcoin.fecha,bitcoin.valor
0,1.7.0,mindicador.cl,2024-04-01T18:00:00.000Z,uf,Unidad de fomento (UF),Pesos,2024-04-01T03:00:00.000Z,37100.68,ivp,Indice de valor promedio (IVP),...,tasa_desempleo,Tasa de desempleo,Porcentaje,2024-02-01T03:00:00.000Z,8.5,bitcoin,Bitcoin,Dólar,2024-02-01T03:00:00.000Z,43061.16

##### **`Forma 1`**

In [6]:
df = pd.DataFrame({'codigo': [respuesta['uf']['codigo'], 
                              respuesta['ivp']['codigo'],
                              respuesta['dolar']['codigo'],
                              respuesta['dolar_intercambio']['codigo'],
                              respuesta['euro']['codigo'],
                              respuesta['ipc']['codigo'],
                              respuesta['utm']['codigo'],
                              respuesta['imacec']['codigo'],
                              respuesta['tpm']['codigo'],
                              respuesta['libra_cobre']['codigo'],
                              respuesta['tasa_desempleo']['codigo'],
                              respuesta['bitcoin']['codigo']],
                    'nombre': [respuesta['uf']['nombre'], 
                               respuesta['ivp']['nombre'],
                               respuesta['dolar']['nombre'],
                               respuesta['dolar_intercambio']['nombre'],
                               respuesta['euro']['nombre'],
                               respuesta['ipc']['nombre'],
                               respuesta['utm']['nombre'],
                               respuesta['imacec']['nombre'],
                               respuesta['tpm']['nombre'],
                               respuesta['libra_cobre']['nombre'],
                               respuesta['tasa_desempleo']['nombre'],
                               respuesta['bitcoin']['nombre']],
                    'unidad_medida': [respuesta['uf']['unidad_medida'], 
                                      respuesta['ivp']['unidad_medida'],
                                      respuesta['dolar']['unidad_medida'],
                                      respuesta['dolar_intercambio']['unidad_medida'],
                                      respuesta['euro']['unidad_medida'],
                                      respuesta['ipc']['unidad_medida'],
                                      respuesta['utm']['unidad_medida'],
                                      respuesta['imacec']['unidad_medida'],
                                      respuesta['tpm']['unidad_medida'],
                                      respuesta['libra_cobre']['unidad_medida'],
                                      respuesta['tasa_desempleo']['unidad_medida'],
                                      respuesta['bitcoin']['unidad_medida']],
                    'valor': [respuesta['uf']['valor'], 
                              respuesta['ivp']['valor'],
                              respuesta['dolar']['valor'],
                              respuesta['dolar_intercambio']['valor'],
                              respuesta['euro']['valor'],
                              respuesta['ipc']['valor'],
                              respuesta['utm']['valor'],
                              respuesta['imacec']['valor'],
                              respuesta['tpm']['valor'],
                              respuesta['libra_cobre']['valor'],
                              respuesta['tasa_desempleo']['valor'],
                              respuesta['bitcoin']['valor']]})
df

,codigo,nombre,unidad_medida,valor
0,uf,Unidad de fomento (UF),Pesos,37100.68
1,ivp,Indice de valor promedio (IVP),Pesos,38457.59
2,dolar,Dólar observado,Pesos,981.71
3,dolar_intercambio,Dólar acuerdo,Pesos,758.87
4,euro,Euro,Pesos,1060.05
5,ipc,Indice de Precios al Consumidor (IPC),Porcentaje,0.60
6,utm,Unidad Tributaria Mensual (UTM),Pesos,65182.00
7,imacec,Imacec,Porcentaje,4.50
8,tpm,Tasa Política Monetaria (TPM),Porcentaje,7.25
9,libra_cobre,Libra de Cobre,Dólar,3.97
10,tasa_desempleo,Tasa de desempleo,Porcentaje,8.50
11,bitcoin,Bitcoin,Dólar,43061.16

### **`Prueba 2`**

In [84]:
import json
import requests
import pandas as pd
import json
import datetime as dt

class Midicador():

    def __init__(self, opcion, indicador, fecha):
         self.opcion = opcion
         self.indicador = indicador
         self.fecha = fecha

    def InfoApi(self):
            if self.opcion == 1:
                url = f'https://mindicador.cl/api/{self.indicador}'
                response = requests.get(url)
                data = json.loads(response.text.encode("utf-8"))                
                df = pd.json_normalize(data, record_path='serie', meta=['codigo','nombre','unidad_medida'])
                df['fecha']= pd.to_datetime(df['fecha']).dt.strftime('%d-%m-%Y')
                return df
            elif self.opcion == 2:    
                # Podemos indicador solo el año o la fecha (dia-mes-año)
                url = f'https://mindicador.cl/api/{self.indicador}/{self.fecha}'
            response = requests.get(url)
            data = json.loads(response.text.encode("utf-8"))
            df = pd.json_normalize(data, record_path='serie')
            df['fecha']= pd.to_datetime(df['fecha']).dt.strftime('%d-%m-%Y')
            return df

#### **Obtener los valores de un indicador especifico para los ultimos 30 dias**

In [76]:
indicadores1 = Midicador(1,'uf','')
indicadores1.InfoApi()

         fecha     valor codigo                  nombre unidad_medida
0   01-04-2024  37100.68     uf  Unidad de fomento (UF)         Pesos
1   31-03-2024  37093.52     uf  Unidad de fomento (UF)         Pesos
2   30-03-2024  37086.36     uf  Unidad de fomento (UF)         Pesos
3   29-03-2024  37079.21     uf  Unidad de fomento (UF)         Pesos
4   28-03-2024  37072.05     uf  Unidad de fomento (UF)         Pesos
5   27-03-2024  37064.90     uf  Unidad de fomento (UF)         Pesos
6   26-03-2024  37057.75     uf  Unidad de fomento (UF)         Pesos
7   25-03-2024  37050.60     uf  Unidad de fomento (UF)         Pesos
8   24-03-2024  37043.45     uf  Unidad de fomento (UF)         Pesos
9   23-03-2024  37036.30     uf  Unidad de fomento (UF)         Pesos
10  22-03-2024  37029.16     uf  Unidad de fomento (UF)         Pesos
11  21-03-2024  37022.01     uf  Unidad de fomento (UF)         Pesos
12  20-03-2024  37014.87     uf  Unidad de fomento (UF)         Pesos
13  19-03-2024  37007.72     uf  Unidad de fomento (UF)         Pesos
14  18-03-2024  37000.58     uf  Unidad de fomento (UF)         Pesos
15  17-03-2024  36993.44     uf  Unidad de fomento (UF)         Pesos
16  16-03-2024  36986.31     uf  Unidad de fomento (UF)         Pesos
17  15-03-2024  36979.17     uf  Unidad de fomento (UF)         Pesos
18  14-03-2024  36972.04     uf  Unidad de fomento (UF)         Pesos
19  13-03-2024  36964.90     uf  Unidad de fomento (UF)         Pesos
20  12-03-2024  36957.77     uf  Unidad de fomento (UF)         Pesos
21  11-03-2024  36950.64     uf  Unidad de fomento (UF)         Pesos
22  10-03-2024  36943.51     uf  Unidad de fomento (UF)         Pesos
23  09-03-2024  36936.38     uf  Unidad de fomento (UF)         Pesos
24  08-03-2024  36927.49     uf  Unidad de fomento (UF)         Pesos
25  07-03-2024  36918.61     uf  Unidad de fomento (UF)         Pesos
26  06-03-2024  36909.73     uf  Unidad de fomento (UF)         Pesos
27  05-03-2024  36900.86     uf  Unidad de fomento (UF)         Pesos
28  04-03-2024  36891.98     uf  Unidad de fomento (UF)         Pesos
29  03-03-2024  36883.11     uf  Unidad de fomento (UF)         Pesos
30  02-03-2024  36874.24     uf  Unidad de fomento (UF)         Pesos

#### **Obtener los valores de un indicador para un año especifico**

In [81]:
indicadores2 = Midicador(2,'dolar','2023')
indicadores2.InfoApi()

          fecha   valor
0    29-12-2023  884.59
1    28-12-2023  886.34
2    27-12-2023  895.77
3    26-12-2023  883.99
4    22-12-2023  872.95
..          ...     ...
242  09-01-2023  846.38
243  06-01-2023  856.31
244  05-01-2023  855.10
245  04-01-2023  852.14
246  03-01-2023  855.86

[247 rows x 2 columns]

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   codigo         12 non-null     object
 1   nombre         12 non-null     object
 2   unidad_medida  12 non-null     object
 3   valor          12 non-null     float64
dtypes: float64(1), object(3)
memory usage: 516.0+ bytes

Podemos cambiar el tipo de dato de la columna fecha de `object` a `datetime` y asi permitirnos ordenar el DF según la columna `fecha`. Aqui `NO` podemos dar un formato especial a la fecha:

In [ ]:
df['fecha']= pd.to_datetime(df['fecha'], format='%d-%m-%Y')
df

Con esta opción solo damos formato a la fecha sin cambiar el tipo de dato, con el cual mantenemos el tipo de dato `object`, el cual no nos permite ordenar el DF según la columna `fecha`:

In [ ]:
df['fecha']= pd.to_datetime(df['fecha']).dt.strftime('%d-%m-%Y')
df

#### **Obtener los valores de un indicador para una fecha especifica**

In [85]:
indicadores3 = Midicador(2, 'uf', '02-03-2023')
indicadores3.InfoApi()

        fecha    valor
0  02-03-2023  35529.9