### **Obtener información de la API generada por el sitio `mindicador.cl/api`**

Utilizamos la siguiente API:

https://mindicador.cl/api/

### **`Prueba 1`**

#### **Conexión a la API**

In [3]:
import requests
import json
import pandas as pd
from pprint import pprint

response = requests.get("https://mindicador.cl/api/")
print(response.status_code) # 200 ==> Quiere decir que la conexión es satisfactoria

200

#### **Extraer información en el tipo `string`**

In [2]:
print(response.text)
print(type(response.text)) # <class 'str'>

{"version":"1.7.0","autor":"mindicador.cl","fecha":"2024-04-01T18:00:00.000Z","uf":{"codigo":"uf","nombre":"Unidad de fomento (UF)","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":37100.68},"ivp":{"codigo":"ivp","nombre":"Indice de valor promedio (IVP)","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":38457.59},"dolar":{"codigo":"dolar","nombre":"Dólar observado","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":981.71},"dolar_intercambio":{"codigo":"dolar_intercambio","nombre":"Dólar acuerdo","unidad_medida":"Pesos","fecha":"2014-11-13T03:00:00.000Z","valor":758.87},"euro":{"codigo":"euro","nombre":"Euro","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":1060.05},"ipc":{"codigo":"ipc","nombre":"Indice de Precios al Consumidor (IPC)","unidad_medida":"Porcentaje","fecha":"2024-02-01T03:00:00.000Z","valor":0.6},"utm":{"codigo":"utm","nombre":"Unidad Tributaria Mensual (UTM)","unidad_medida":"Pesos","fecha":"2024-04-01T03:00:00.000Z","valor":65182},"imacec":{"codigo":"imacec","nombre":"Imacec","unidad_medida":"Porcentaje","fecha":"2024-02-01T03:00:00.000Z","valor":4.5},"tpm":{"codigo":"tpm","nombre":"Tasa Política Monetaria (TPM)","unidad_medida":"Porcentaje","fecha":"2024-04-01T03:00:00.000Z","valor":7.25},"libra_cobre":{"codigo":"libra_cobre","nombre":"Libra de Cobre","unidad_medida":"Dólar","fecha":"2024-04-01T03:00:00.000Z","valor":3.97},"tasa_desempleo":{"codigo":"tasa_desempleo","nombre":"Tasa de desempleo","unidad_medida":"Porcentaje","fecha":"2024-02-01T03:00:00.000Z","valor":8.5},"bitcoin":{"codigo":"bitcoin","nombre":"Bitcoin","unidad_medida":"Dólar","fecha":"2024-02-01T03:00:00.000Z","valor":43061.16}}
<class 'str'>

#### **Extraer información en el tipo `diccionario`**

In [3]:
pprint(response.json())
print(type(response.json())) # <class 'dict'>

{'autor': 'mindicador.cl',
 'bitcoin': {'codigo': 'bitcoin',
             'fecha': '2024-02-01T03:00:00.000Z',
             'nombre': 'Bitcoin',
             'unidad_medida': 'Dólar',
             'valor': 43061.16},
 'dolar': {'codigo': 'dolar',
           'fecha': '2024-04-01T03:00:00.000Z',
           'nombre': 'Dólar observado',
           'unidad_medida': 'Pesos',
           'valor': 981.71},
 'dolar_intercambio': {'codigo': 'dolar_intercambio',
                       'fecha': '2014-11-13T03:00:00.000Z',
                       'nombre': 'Dólar acuerdo',
                       'unidad_medida': 'Pesos',
                       'valor': 758.87},
 'euro': {'codigo': 'euro',
          'fecha': '2024-04-01T03:00:00.000Z',
          'nombre': 'Euro',
          'unidad_medida': 'Pesos',
          'valor': 1060.05},
 'fecha': '2024-04-01T18:00:00.000Z',
 'imacec': {'codigo': 'imacec',
            'fecha': '2024-02-01T03:00:00.000Z',
            'nombre': 'Imacec',
            'unidad_medida': 'Porcentaje',
            'valor': 4.5},
 'ipc': {'codigo': 'ipc',
         'fecha': '2024-02-01T03:00:00.000Z',
         'nombre': 'Indice de Precios al Consumidor (IPC)',
         'unidad_medida': 'Porcentaje',
         'valor': 0.6},
 'ivp': {'codigo': 'ivp',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Indice de valor promedio (IVP)',
         'unidad_medida': 'Pesos',
         'valor': 38457.59},
 'libra_cobre': {'codigo': 'libra_cobre',
                 'fecha': '2024-04-01T03:00:00.000Z',
                 'nombre': 'Libra de Cobre',
                 'unidad_medida': 'Dólar',
                 'valor': 3.97},
 'tasa_desempleo': {'codigo': 'tasa_desempleo',
                    'fecha': '2024-02-01T03:00:00.000Z',
                    'nombre': 'Tasa de desempleo',
                    'unidad_medida': 'Porcentaje',
                    'valor': 8.5},
 'tpm': {'codigo': 'tpm',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Tasa Política Monetaria (TPM)',
         'unidad_medida': 'Porcentaje',
         'valor': 7.25},
 'uf': {'codigo': 'uf',
        'fecha': '2024-04-01T03:00:00.000Z',
        'nombre': 'Unidad de fomento (UF)',
        'unidad_medida': 'Pesos',
        'valor': 37100.68},
 'utm': {'codigo': 'utm',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Unidad Tributaria Mensual (UTM)',
         'unidad_medida': 'Pesos',
         'valor': 65182},
 'version': '1.7.0'}
<class 'dict'>

In [4]:
respuesta = json.loads(response.text)
pprint(respuesta)
print(type(respuesta)) # <class 'dict'>

{'autor': 'mindicador.cl',
 'bitcoin': {'codigo': 'bitcoin',
             'fecha': '2024-04-01T03:00:00.000Z',
             'nombre': 'Bitcoin',
             'unidad_medida': 'Dólar',
             'valor': 69701.3},
 'dolar': {'codigo': 'dolar',
           'fecha': '2024-04-03T03:00:00.000Z',
           'nombre': 'Dólar observado',
           'unidad_medida': 'Pesos',
           'valor': 979.96},
 'dolar_intercambio': {'codigo': 'dolar_intercambio',
                       'fecha': '2014-11-13T03:00:00.000Z',
                       'nombre': 'Dólar acuerdo',
                       'unidad_medida': 'Pesos',
                       'valor': 758.87},
 'euro': {'codigo': 'euro',
          'fecha': '2024-04-03T03:00:00.000Z',
          'nombre': 'Euro',
          'unidad_medida': 'Pesos',
          'valor': 1055.08},
 'fecha': '2024-04-03T11:00:00.000Z',
 'imacec': {'codigo': 'imacec',
            'fecha': '2024-02-01T03:00:00.000Z',
            'nombre': 'Imacec',
            'unidad_medida': 'Porcentaje',
            'valor': 4.5},
 'ipc': {'codigo': 'ipc',
         'fecha': '2024-02-01T03:00:00.000Z',
         'nombre': 'Indice de Precios al Consumidor (IPC)',
         'unidad_medida': 'Porcentaje',
         'valor': 0.6},
 'ivp': {'codigo': 'ivp',
         'fecha': '2024-04-03T03:00:00.000Z',
         'nombre': 'Indice de valor promedio (IVP)',
         'unidad_medida': 'Pesos',
         'valor': 38468.47},
 'libra_cobre': {'codigo': 'libra_cobre',
                 'fecha': '2024-04-03T03:00:00.000Z',
                 'nombre': 'Libra de Cobre',
                 'unidad_medida': 'Dólar',
                 'valor': 3.98},
 'tasa_desempleo': {'codigo': 'tasa_desempleo',
                    'fecha': '2024-02-01T03:00:00.000Z',
                    'nombre': 'Tasa de desempleo',
                    'unidad_medida': 'Porcentaje',
                    'valor': 8.5},
 'tpm': {'codigo': 'tpm',
         'fecha': '2024-04-03T03:00:00.000Z',
         'nombre': 'Tasa Política Monetaria (TPM)',
         'unidad_medida': 'Porcentaje',
         'valor': 6.5},
 'uf': {'codigo': 'uf',
        'fecha': '2024-04-03T03:00:00.000Z',
        'nombre': 'Unidad de fomento (UF)',
        'unidad_medida': 'Pesos',
        'valor': 37115},
 'utm': {'codigo': 'utm',
         'fecha': '2024-04-01T03:00:00.000Z',
         'nombre': 'Unidad Tributaria Mensual (UTM)',
         'unidad_medida': 'Pesos',
         'valor': 65182},
 'version': '1.7.0'}
<class 'dict'>

#### **Normalizar data en un Dataframe**

Esta no es la mejor manera de normalizar un json, dado que nos entrega una fila y 63 columnas:

In [5]:
df = pd.json_normalize(respuesta)
df

,version,autor,fecha,uf.codigo,uf.nombre,uf.unidad_medida,uf.fecha,uf.valor,ivp.codigo,ivp.nombre,...,tasa_desempleo.codigo,tasa_desempleo.nombre,tasa_desempleo.unidad_medida,tasa_desempleo.fecha,tasa_desempleo.valor,bitcoin.codigo,bitcoin.nombre,bitcoin.unidad_medida,bitcoin.fecha,bitcoin.valor
0,1.7.0,mindicador.cl,2024-04-01T18:00:00.000Z,uf,Unidad de fomento (UF),Pesos,2024-04-01T03:00:00.000Z,37100.68,ivp,Indice de valor promedio (IVP),...,tasa_desempleo,Tasa de desempleo,Porcentaje,2024-02-01T03:00:00.000Z,8.5,bitcoin,Bitcoin,Dólar,2024-02-01T03:00:00.000Z,43061.16

##### **`Forma 1`**

In [6]:
df = pd.DataFrame({'codigo': [respuesta['uf']['codigo'], 
                              respuesta['ivp']['codigo'],
                              respuesta['dolar']['codigo'],
                              respuesta['dolar_intercambio']['codigo'],
                              respuesta['euro']['codigo'],
                              respuesta['ipc']['codigo'],
                              respuesta['utm']['codigo'],
                              respuesta['imacec']['codigo'],
                              respuesta['tpm']['codigo'],
                              respuesta['libra_cobre']['codigo'],
                              respuesta['tasa_desempleo']['codigo'],
                              respuesta['bitcoin']['codigo']],
                    'nombre': [respuesta['uf']['nombre'], 
                               respuesta['ivp']['nombre'],
                               respuesta['dolar']['nombre'],
                               respuesta['dolar_intercambio']['nombre'],
                               respuesta['euro']['nombre'],
                               respuesta['ipc']['nombre'],
                               respuesta['utm']['nombre'],
                               respuesta['imacec']['nombre'],
                               respuesta['tpm']['nombre'],
                               respuesta['libra_cobre']['nombre'],
                               respuesta['tasa_desempleo']['nombre'],
                               respuesta['bitcoin']['nombre']],
                    'unidad_medida': [respuesta['uf']['unidad_medida'], 
                                      respuesta['ivp']['unidad_medida'],
                                      respuesta['dolar']['unidad_medida'],
                                      respuesta['dolar_intercambio']['unidad_medida'],
                                      respuesta['euro']['unidad_medida'],
                                      respuesta['ipc']['unidad_medida'],
                                      respuesta['utm']['unidad_medida'],
                                      respuesta['imacec']['unidad_medida'],
                                      respuesta['tpm']['unidad_medida'],
                                      respuesta['libra_cobre']['unidad_medida'],
                                      respuesta['tasa_desempleo']['unidad_medida'],
                                      respuesta['bitcoin']['unidad_medida']],
                    'valor': [respuesta['uf']['valor'], 
                              respuesta['ivp']['valor'],
                              respuesta['dolar']['valor'],
                              respuesta['dolar_intercambio']['valor'],
                              respuesta['euro']['valor'],
                              respuesta['ipc']['valor'],
                              respuesta['utm']['valor'],
                              respuesta['imacec']['valor'],
                              respuesta['tpm']['valor'],
                              respuesta['libra_cobre']['valor'],
                              respuesta['tasa_desempleo']['valor'],
                              respuesta['bitcoin']['valor']]})
df

,codigo,nombre,unidad_medida,valor
0,uf,Unidad de fomento (UF),Pesos,37100.68
1,ivp,Indice de valor promedio (IVP),Pesos,38457.59
2,dolar,Dólar observado,Pesos,981.71
3,dolar_intercambio,Dólar acuerdo,Pesos,758.87
4,euro,Euro,Pesos,1060.05
5,ipc,Indice de Precios al Consumidor (IPC),Porcentaje,0.60
6,utm,Unidad Tributaria Mensual (UTM),Pesos,65182.00
7,imacec,Imacec,Porcentaje,4.50
8,tpm,Tasa Política Monetaria (TPM),Porcentaje,7.25
9,libra_cobre,Libra de Cobre,Dólar,3.97
10,tasa_desempleo,Tasa de desempleo,Porcentaje,8.50
11,bitcoin,Bitcoin,Dólar,43061.16

##### **`Forma 2`**

In [8]:
list(respuesta.keys())[3:]

['uf',
 'ivp',
 'dolar',
 'dolar_intercambio',
 'euro',
 'ipc',
 'utm',
 'imacec',
 'tpm',
 'libra_cobre',
 'tasa_desempleo',
 'bitcoin']

In [12]:
df_final = pd.DataFrame()

for i in list(respuesta.keys())[3:]:
    fila = pd.json_normalize(respuesta[i])
    df_final = pd.concat([df_final, fila])

df_final

,codigo,nombre,unidad_medida,fecha,valor
0,uf,Unidad de fomento (UF),Pesos,2024-04-03T03:00:00.000Z,37115.00
0,ivp,Indice de valor promedio (IVP),Pesos,2024-04-03T03:00:00.000Z,38468.47
0,dolar,Dólar observado,Pesos,2024-04-03T03:00:00.000Z,979.96
0,dolar_intercambio,Dólar acuerdo,Pesos,2014-11-13T03:00:00.000Z,758.87
0,euro,Euro,Pesos,2024-04-03T03:00:00.000Z,1055.08
0,ipc,Indice de Precios al Consumidor (IPC),Porcentaje,2024-02-01T03:00:00.000Z,0.60
0,utm,Unidad Tributaria Mensual (UTM),Pesos,2024-04-01T03:00:00.000Z,65182.00
0,imacec,Imacec,Porcentaje,2024-02-01T03:00:00.000Z,4.50
0,tpm,Tasa Política Monetaria (TPM),Porcentaje,2024-04-03T03:00:00.000Z,6.50
0,libra_cobre,Libra de Cobre,Dólar,2024-04-03T03:00:00.000Z,3.98
0,tasa_desempleo,Tasa de desempleo,Porcentaje,2024-02-01T03:00:00.000Z,8.50
0,bitcoin,Bitcoin,Dólar,2024-04-01T03:00:00.000Z,69701.30

### **`Prueba 2`**

##### **Prueba 1 orden columna `fecha`**

In [16]:
import json
import requests
import pandas as pd
import datetime as dt

url = f'https://mindicador.cl/api/uf/2024'
response = requests.get(url)
data = json.loads(response.text.encode("utf-8"))
df = pd.json_normalize(data, record_path='serie')
df

                        fecha     valor
0    2024-06-09T04:00:00.000Z  37493.16
1    2024-06-08T04:00:00.000Z  37487.13
2    2024-06-07T04:00:00.000Z  37481.10
3    2024-06-06T04:00:00.000Z  37475.07
4    2024-06-05T04:00:00.000Z  37469.04
..                        ...       ...
156  2024-01-05T03:00:00.000Z  36830.78
157  2024-01-04T03:00:00.000Z  36822.49
158  2024-01-03T03:00:00.000Z  36814.21
159  2024-01-02T03:00:00.000Z  36805.92
160  2024-01-01T03:00:00.000Z  36797.64

[161 rows x 2 columns]

In [18]:
# Se ordena la columna de manera ascendente

import json
import requests
import pandas as pd
import datetime as dt

url = f'https://mindicador.cl/api/uf/2024'
response = requests.get(url)
data = json.loads(response.text.encode("utf-8"))
df = pd.json_normalize(data, record_path='serie')
df.sort_values('fecha')

                        fecha     valor
160  2024-01-01T03:00:00.000Z  36797.64
159  2024-01-02T03:00:00.000Z  36805.92
158  2024-01-03T03:00:00.000Z  36814.21
157  2024-01-04T03:00:00.000Z  36822.49
156  2024-01-05T03:00:00.000Z  36830.78
..                        ...       ...
4    2024-06-05T04:00:00.000Z  37469.04
3    2024-06-06T04:00:00.000Z  37475.07
2    2024-06-07T04:00:00.000Z  37481.10
1    2024-06-08T04:00:00.000Z  37487.13
0    2024-06-09T04:00:00.000Z  37493.16

[161 rows x 2 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fecha   161 non-null    object
 1   valor   161 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.6+ KB

##### **Prueba 2 orden y modificación columna `fecha`**

In [4]:
import json
import requests
import pandas as pd
from datetime import datetime

url = f'https://mindicador.cl/api/uf'
response = requests.get(url)
data = json.loads(response.text.encode("utf-8"))
df = pd.json_normalize(data, record_path='serie')
df['fecha'] = df['fecha'].apply(lambda x:datetime.fromisoformat(x[:-1]).date())
df

         fecha     valor
0   2024-05-19  37366.70
1   2024-05-18  37360.69
2   2024-05-17  37354.68
3   2024-05-16  37348.67
4   2024-05-15  37342.66
5   2024-05-14  37336.65
6   2024-05-13  37330.65
7   2024-05-12  37324.64
8   2024-05-11  37318.64
9   2024-05-10  37312.63
10  2024-05-09  37306.63
11  2024-05-08  37301.67
12  2024-05-07  37296.70
13  2024-05-06  37291.74
14  2024-05-05  37286.78
15  2024-05-04  37281.82
16  2024-05-03  37276.86
17  2024-05-02  37271.90
18  2024-05-01  37266.94
19  2024-04-30  37261.98
20  2024-04-29  37257.02
21  2024-04-28  37252.06
22  2024-04-27  37247.11
23  2024-04-26  37242.15
24  2024-04-25  37237.20
25  2024-04-24  37232.24
26  2024-04-23  37227.29
27  2024-04-22  37222.33
28  2024-04-21  37217.38
29  2024-04-20  37212.43
30  2024-04-19  37207.48

In [52]:
import json
import requests
import pandas as pd
from datetime import datetime

url = f'https://mindicador.cl/api/uf/2024'
response = requests.get(url)
data = json.loads(response.text.encode("utf-8"))
df = pd.json_normalize(data, record_path='serie')
df['fecha'] = df['fecha'].apply(lambda x:datetime.fromisoformat(x[:-1]).date())
df.sort_values('fecha')

          fecha     valor
160  2024-01-01  36797.64
159  2024-01-02  36805.92
158  2024-01-03  36814.21
157  2024-01-04  36822.49
156  2024-01-05  36830.78
..          ...       ...
4    2024-06-05  37469.04
3    2024-06-06  37475.07
2    2024-06-07  37481.10
1    2024-06-08  37487.13
0    2024-06-09  37493.16

[161 rows x 2 columns]

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fecha   161 non-null    object
 1   valor   161 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.6+ KB

##### **Prueba 3 orden y modificación columna `fecha`**

Con esta opción solo damos formato a la fecha sin cambiar el tipo de dato, con el cual mantenemos el tipo de dato `object`, el cual no nos permite ordenar el DF según la columna `fecha`:

In [21]:
import json
import requests
import pandas as pd
import datetime as dt

url = f'https://mindicador.cl/api/uf/2024'
response = requests.get(url)
data = json.loads(response.text.encode("utf-8"))
df = pd.json_normalize(data, record_path='serie')
df['fecha']= pd.to_datetime(df['fecha']).dt.strftime('%d-%m-%Y')
df

          fecha     valor
0    09-06-2024  37493.16
1    08-06-2024  37487.13
2    07-06-2024  37481.10
3    06-06-2024  37475.07
4    05-06-2024  37469.04
..          ...       ...
156  05-01-2024  36830.78
157  04-01-2024  36822.49
158  03-01-2024  36814.21
159  02-01-2024  36805.92
160  01-01-2024  36797.64

[161 rows x 2 columns]

In [22]:
# No se ordena el dataframe segun la columna fecha
import json
import requests
import pandas as pd
import datetime as dt

url = f'https://mindicador.cl/api/uf/2024'
response = requests.get(url)
data = json.loads(response.text.encode("utf-8"))
df = pd.json_normalize(data, record_path='serie')
df['fecha']= pd.to_datetime(df['fecha']).dt.strftime('%d-%m-%Y')
df.sort_values('fecha')
df

          fecha     valor
0    09-06-2024  37493.16
1    08-06-2024  37487.13
2    07-06-2024  37481.10
3    06-06-2024  37475.07
4    05-06-2024  37469.04
..          ...       ...
156  05-01-2024  36830.78
157  04-01-2024  36822.49
158  03-01-2024  36814.21
159  02-01-2024  36805.92
160  01-01-2024  36797.64

[161 rows x 2 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fecha   161 non-null    object
 1   valor   161 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.6+ KB

#### **Obtener los valores de un indicador especifico para los ultimos 30 dias**

In [1]:
from scripts.mindicador_class import Mindicador

response = Mindicador('uf')
response.obtener_ultimos_30_dias()

2024-05-19 01:58:00,885 - obtener_ultimos_30_dias - INFO - La respuesta fue exitosa
2024-05-19 01:58:00,896 - obtener_ultimos_30_dias - INFO - Se creó el Dataframe de manera exitosa

         fecha     valor codigo                  nombre unidad_medida
30  2024-04-19  37207.48     uf  Unidad de fomento (UF)         Pesos
29  2024-04-20  37212.43     uf  Unidad de fomento (UF)         Pesos
28  2024-04-21  37217.38     uf  Unidad de fomento (UF)         Pesos
27  2024-04-22  37222.33     uf  Unidad de fomento (UF)         Pesos
26  2024-04-23  37227.29     uf  Unidad de fomento (UF)         Pesos
25  2024-04-24  37232.24     uf  Unidad de fomento (UF)         Pesos
24  2024-04-25  37237.20     uf  Unidad de fomento (UF)         Pesos
23  2024-04-26  37242.15     uf  Unidad de fomento (UF)         Pesos
22  2024-04-27  37247.11     uf  Unidad de fomento (UF)         Pesos
21  2024-04-28  37252.06     uf  Unidad de fomento (UF)         Pesos
20  2024-04-29  37257.02     uf  Unidad de fomento (UF)         Pesos
19  2024-04-30  37261.98     uf  Unidad de fomento (UF)         Pesos
18  2024-05-01  37266.94     uf  Unidad de fomento (UF)         Pesos
17  2024-05-02  37271.90     uf  Unidad de fomento (UF)         Pesos
16  2024-05-03  37276.86     uf  Unidad de fomento (UF)         Pesos
15  2024-05-04  37281.82     uf  Unidad de fomento (UF)         Pesos
14  2024-05-05  37286.78     uf  Unidad de fomento (UF)         Pesos
13  2024-05-06  37291.74     uf  Unidad de fomento (UF)         Pesos
12  2024-05-07  37296.70     uf  Unidad de fomento (UF)         Pesos
11  2024-05-08  37301.67     uf  Unidad de fomento (UF)         Pesos
10  2024-05-09  37306.63     uf  Unidad de fomento (UF)         Pesos
9   2024-05-10  37312.63     uf  Unidad de fomento (UF)         Pesos
8   2024-05-11  37318.64     uf  Unidad de fomento (UF)         Pesos
7   2024-05-12  37324.64     uf  Unidad de fomento (UF)         Pesos
6   2024-05-13  37330.65     uf  Unidad de fomento (UF)         Pesos
5   2024-05-14  37336.65     uf  Unidad de fomento (UF)         Pesos
4   2024-05-15  37342.66     uf  Unidad de fomento (UF)         Pesos
3   2024-05-16  37348.67     uf  Unidad de fomento (UF)         Pesos
2   2024-05-17  37354.68     uf  Unidad de fomento (UF)         Pesos
1   2024-05-18  37360.69     uf  Unidad de fomento (UF)         Pesos
0   2024-05-19  37366.70     uf  Unidad de fomento (UF)         Pesos

#### **Obtener los valores de un indicador para un año especifico**

In [1]:
from scripts.mindicador_class import Mindicador

response = Mindicador('uf')
response.obtener_anio('2023')

2024-05-19 02:02:27,087 - obtener_anio - INFO - La respuesta fue exitosa

          fecha     valor
364  2023-01-01  35122.26
363  2023-01-02  35133.53
362  2023-01-03  35144.81
361  2023-01-04  35156.09
360  2023-01-05  35167.38
..          ...       ...
4    2023-12-27  36756.26
3    2023-12-28  36764.54
2    2023-12-29  36772.81
1    2023-12-30  36781.09
0    2023-12-31  36789.36

[365 rows x 2 columns]

#### **Obtener los valores de un indicador para una fecha especifica**

In [3]:
from scripts.mindicador_class import Mindicador

response = Mindicador('uf')
response.obtener_anio('06-03-2023')

2024-05-19 02:06:22,054 - obtener_anio - INFO - La respuesta fue exitosa

        fecha     valor
0  2023-03-06  35570.37

#### **Obtener los valores de todos los indicadores para el dia actual**

In [4]:
from scripts.mindicador_class import Mindicador

response = Mindicador('')
response.obtener_full_indicadores()

2024-05-19 02:07:13,622 - obtener_full_indicadores - INFO - La respuesta fue exitosa

,codigo,nombre,unidad_medida,fecha,valor
0,uf,Unidad de fomento (UF),Pesos,2024-05-19T04:00:00.000Z,37366.70
0,ivp,Indice de valor promedio (IVP),Pesos,2024-05-19T04:00:00.000Z,38694.96
0,dolar,Dólar observado,Pesos,2024-05-17T04:00:00.000Z,901.53
0,dolar_intercambio,Dólar acuerdo,Pesos,2014-11-13T03:00:00.000Z,758.87
0,euro,Euro,Pesos,2024-05-17T04:00:00.000Z,979.82
0,ipc,Indice de Precios al Consumidor (IPC),Porcentaje,2024-04-01T03:00:00.000Z,0.50
0,utm,Unidad Tributaria Mensual (UTM),Pesos,2024-05-01T04:00:00.000Z,65443.00
0,imacec,Imacec,Porcentaje,2024-03-01T03:00:00.000Z,0.80
0,tpm,Tasa Política Monetaria (TPM),Porcentaje,2024-05-17T04:00:00.000Z,6.50
0,libra_cobre,Libra de Cobre,Dólar,2024-05-17T04:00:00.000Z,4.59
0,tasa_desempleo,Tasa de desempleo,Porcentaje,2024-03-01T03:00:00.000Z,8.68
0,bitcoin,Bitcoin,Dólar,2024-05-15T04:00:00.000Z,66239.13

In [5]:
from scripts.mindicador_class import Mindicador

response = Mindicador('uf')
response.obtener_full_indicadores()

2024-05-19 02:07:29,940 - obtener_full_indicadores - INFO - La respuesta fue exitosa

,codigo,nombre,unidad_medida,fecha,valor
0,uf,Unidad de fomento (UF),Pesos,2024-05-19T04:00:00.000Z,37366.70
0,ivp,Indice de valor promedio (IVP),Pesos,2024-05-19T04:00:00.000Z,38694.96
0,dolar,Dólar observado,Pesos,2024-05-17T04:00:00.000Z,901.53
0,dolar_intercambio,Dólar acuerdo,Pesos,2014-11-13T03:00:00.000Z,758.87
0,euro,Euro,Pesos,2024-05-17T04:00:00.000Z,979.82
0,ipc,Indice de Precios al Consumidor (IPC),Porcentaje,2024-04-01T03:00:00.000Z,0.50
0,utm,Unidad Tributaria Mensual (UTM),Pesos,2024-05-01T04:00:00.000Z,65443.00
0,imacec,Imacec,Porcentaje,2024-03-01T03:00:00.000Z,0.80
0,tpm,Tasa Política Monetaria (TPM),Porcentaje,2024-05-17T04:00:00.000Z,6.50
0,libra_cobre,Libra de Cobre,Dólar,2024-05-17T04:00:00.000Z,4.59
0,tasa_desempleo,Tasa de desempleo,Porcentaje,2024-03-01T03:00:00.000Z,8.68
0,bitcoin,Bitcoin,Dólar,2024-05-15T04:00:00.000Z,66239.13