### **Obtener informacion de archivo JSON desde un repositorio de Github, normalizarla en un Dataframe y exportarla a un archivo CSV**

### **`Prueba 1`**

#### **Conexión a la API**

Utilizamos el siguiente enlace:

https://raw.githubusercontent.com/zyrikby/website_related/master/2021-04-flattening-json-using-pandas/vertx_example.json

In [5]:
import requests
import json
import pandas as pd

response = requests.get("https://raw.githubusercontent.com/zyrikby/website_related/master/2021-04-flattening-json-using-pandas/vertx_example.json")
print(response.status_code) # 200 ==> Quiere decir que la conexión es satisfactoria

200

#### **Extraer información en el tipo `lista`**

In [2]:
print(response.json())
print(type(response.json())) # <class 'list'>

[{'matches': [{'album': 'Elephunk', 'artist': 'Black Eyed Peas; Papa Roach', 'segments': [{'duration': 24.9375, 'que_offset': 0.0, 'ref_offset': 18.0}], 'title': 'Anxiety', 'type': 'music', 'uid': 6475547275973858650}, {'imdb_id': 365957, 'segments': [{'duration': 24.9375, 'que_offset': 0.0, 'ref_offset': 3500.625}], 'title': 'You Got Served', 'type': 'movie', 'uid': 1566530810344932800, 'year': 2004}], 'media_type': 'audio', 'source_path': 'sample.mp4', 'source_uid': 1758730481226206085, 'status': 'succeeded'}, {'matches': [{'imdb_id': 332452, 'segments': [{'duration': 21.0, 'que_offset': 0.0, 'ref_offset': 8608.5}], 'title': 'Troy', 'type': 'movie', 'uid': 1342729426672482861, 'year': 2004}], 'media_type': 'video', 'source_path': 'sample.mp4', 'source_uid': 1758730481226206085, 'status': 'succeeded'}]
<class 'list'>

In [6]:
respuesta = json.loads(response.text)
print(respuesta)
print(type(respuesta)) # <class 'list'>

[{'matches': [{'album': 'Elephunk', 'artist': 'Black Eyed Peas; Papa Roach', 'segments': [{'duration': 24.9375, 'que_offset': 0.0, 'ref_offset': 18.0}], 'title': 'Anxiety', 'type': 'music', 'uid': 6475547275973858650}, {'imdb_id': 365957, 'segments': [{'duration': 24.9375, 'que_offset': 0.0, 'ref_offset': 3500.625}], 'title': 'You Got Served', 'type': 'movie', 'uid': 1566530810344932800, 'year': 2004}], 'media_type': 'audio', 'source_path': 'sample.mp4', 'source_uid': 1758730481226206085, 'status': 'succeeded'}, {'matches': [{'imdb_id': 332452, 'segments': [{'duration': 21.0, 'que_offset': 0.0, 'ref_offset': 8608.5}], 'title': 'Troy', 'type': 'movie', 'uid': 1342729426672482861, 'year': 2004}], 'media_type': 'video', 'source_path': 'sample.mp4', 'source_uid': 1758730481226206085, 'status': 'succeeded'}]
<class 'list'>

#### **Extraer información de la API y normarlizar la data en un Dataframe**

##### **`Forma 1`**

In [12]:
flattened_data = []
for mte in respuesta:
        for m in mte['matches']:
            print(m)

{'album': 'Elephunk', 'artist': 'Black Eyed Peas; Papa Roach', 'segments': [{'duration': 24.9375, 'que_offset': 0.0, 'ref_offset': 18.0}], 'title': 'Anxiety', 'type': 'music', 'uid': 6475547275973858650}
{'imdb_id': 365957, 'segments': [{'duration': 24.9375, 'que_offset': 0.0, 'ref_offset': 3500.625}], 'title': 'You Got Served', 'type': 'movie', 'uid': 1566530810344932800, 'year': 2004}
{'imdb_id': 332452, 'segments': [{'duration': 21.0, 'que_offset': 0.0, 'ref_offset': 8608.5}], 'title': 'Troy', 'type': 'movie', 'uid': 1342729426672482861, 'year': 2004}

In [5]:
def load_vertx_data():
    flattened_data = []
    for mte in respuesta:
        que_uid = mte.get('source_uid', pd.NA)
        media_type = mte.get('media_type', pd.NA)
        source_path = mte.get('source_path', pd.NA)
        status = mte.get('status', pd.NA)
        for m in mte['matches']:
            artist = m.get('artist', pd.NA)
            album = m.get('album', pd.NA)
            title = m.get('title', pd.NA)
            type_ = m.get('type', pd.NA)
            ref_uid = m.get('uid', pd.NA)
            imdb_id = m.get('imdb_id', pd.NA)
            year = m.get('year', pd.NA)
            for s in m['segments']:
                duration = s['duration']
                que_offset = s['que_offset']
                ref_offset = s['ref_offset']
                entry = {
                        'que_uid': que_uid,
                        'media_type': media_type,
                        'source_path': source_path,
                        'status': status,
                        'artist': artist,
                        'album': album,
                        'title': title,
                        'type': type_,
                        'ref_uid': ref_uid,
                        'imdb_id': imdb_id,
                        'year': year,
                        'que_offset': que_offset,
                        'ref_offset': ref_offset,
                        'duration': duration,
                        }
                flattened_data.append(entry)
    
    print(flattened_data)
    
    return pd.DataFrame(flattened_data)

In [6]:
df = load_vertx_data()
df

[{'que_uid': 1758730481226206085, 'media_type': 'audio', 'source_path': 'sample.mp4', 'status': 'succeeded', 'artist': 'Black Eyed Peas; Papa Roach', 'album': 'Elephunk', 'title': 'Anxiety', 'type': 'music', 'ref_uid': 6475547275973858650, 'imdb_id': <NA>, 'year': <NA>, 'que_offset': 0.0, 'ref_offset': 18.0, 'duration': 24.9375}, {'que_uid': 1758730481226206085, 'media_type': 'audio', 'source_path': 'sample.mp4', 'status': 'succeeded', 'artist': <NA>, 'album': <NA>, 'title': 'You Got Served', 'type': 'movie', 'ref_uid': 1566530810344932800, 'imdb_id': 365957, 'year': 2004, 'que_offset': 0.0, 'ref_offset': 3500.625, 'duration': 24.9375}, {'que_uid': 1758730481226206085, 'media_type': 'video', 'source_path': 'sample.mp4', 'status': 'succeeded', 'artist': <NA>, 'album': <NA>, 'title': 'Troy', 'type': 'movie', 'ref_uid': 1342729426672482861, 'imdb_id': 332452, 'year': 2004, 'que_offset': 0.0, 'ref_offset': 8608.5, 'duration': 21.0}]

,que_uid,media_type,source_path,status,artist,album,title,type,ref_uid,imdb_id,year,que_offset,ref_offset,duration
0,1758730481226206085,audio,sample.mp4,succeeded,Black Eyed Peas; Papa Roach,Elephunk,Anxiety,music,6475547275973858650,<NA>,<NA>,0.0,18.000,24.9375
1,1758730481226206085,audio,sample.mp4,succeeded,<NA>,<NA>,You Got Served,movie,1566530810344932800,365957,2004,0.0,3500.625,24.9375
2,1758730481226206085,video,sample.mp4,succeeded,<NA>,<NA>,Troy,movie,1342729426672482861,332452,2004,0.0,8608.500,21.0000

##### **`Forma 2`**

In [7]:
def cargar_vertx_data_usando_json_normalize():
    df = pd.json_normalize(
        respuesta,
        record_path=['matches', 'segments'],
        meta=['source_uid', 'media_type', 'source_path', 'status', 
              ['matches', 'uid'], 
              ['matches', 'artist'],
              ['matches', 'album'],
              ['matches', 'title'],
              ['matches', 'type'],
              ['matches', 'imdb_id'],
              ['matches', 'year'],
        ],
        errors='ignore'
    )
    df = df.rename(
        columns={
            'source_uid': 'que_uid', 
            'matches.uid': 'ref_uid',
            'matches.artist': 'artist',
            'matches.album': 'album',
            'matches.title': 'title',
            'matches.type': 'type',
            'matches.imdb_id': 'imdb_id',
            'matches.year': 'year',
        },
    )
    
    return df

In [9]:
new_df =  cargar_vertx_data_usando_json_normalize()
new_df

,duration,que_offset,ref_offset,que_uid,media_type,source_path,status,ref_uid,artist,album,title,type,imdb_id,year
0,24.9375,0.0,18.000,1758730481226206085,audio,sample.mp4,succeeded,6475547275973858650,Black Eyed Peas; Papa Roach,Elephunk,Anxiety,music,NaN,NaN
1,24.9375,0.0,3500.625,1758730481226206085,audio,sample.mp4,succeeded,1566530810344932800,NaN,NaN,You Got Served,movie,365957,2004
2,21.0000,0.0,8608.500,1758730481226206085,video,sample.mp4,succeeded,1342729426672482861,NaN,NaN,Troy,movie,332452,2004

#### **Exportar Dataframe en un archivo `CSV`**

In [10]:
new_df.to_csv("vertx_data.csv", index=False)

### **`Prueba 2`**

#### **Crear objetos y funciones que faciliten la llamada a la API**

In [1]:
import json
import requests
import pandas as pd
import json

class Github_Api():

    def __init__(self):
        pass

    def devolverDataframe(self):
        url = 'https://raw.githubusercontent.com/zyrikby/website_related/master/2021-04-flattening-json-using-pandas/vertx_example.json'
        response = requests.get(url)
        data = json.loads(response.text.encode("utf-8"))                
        df = pd.json_normalize(data, record_path=['matches', 'segments'], record_prefix='segments.',
                                     meta=['source_uid', 'media_type', 'source_path', 'status', 
                                            ['matches', 'uid'], 
                                            ['matches', 'artist'],
                                            ['matches', 'album'],
                                            ['matches', 'title'],
                                            ['matches', 'type'],
                                            ['matches', 'imdb_id'],
                                            ['matches', 'year']],
                                     errors='ignore')
        return df
    
    def exportarCSV(self):
        self.devolverDataframe().to_csv("vertx_data2.csv", index=False)

In [2]:
api1 = Github_Api()

In [3]:
api1.devolverDataframe()

,segments.duration,segments.que_offset,segments.ref_offset,source_uid,media_type,source_path,status,matches.uid,matches.artist,matches.album,matches.title,matches.type,matches.imdb_id,matches.year
0,24.9375,0.0,18.000,1758730481226206085,audio,sample.mp4,succeeded,6475547275973858650,Black Eyed Peas; Papa Roach,Elephunk,Anxiety,music,NaN,NaN
1,24.9375,0.0,3500.625,1758730481226206085,audio,sample.mp4,succeeded,1566530810344932800,NaN,NaN,You Got Served,movie,365957,2004
2,21.0000,0.0,8608.500,1758730481226206085,video,sample.mp4,succeeded,1342729426672482861,NaN,NaN,Troy,movie,332452,2004

In [4]:
api1.exportarCSV()