### **Obtener información de la API generada por el sitio `randomuser.me/api` y normalizarla en un Dataframe**

Utilizamos la siguiente API:

https://randomuser.me/api/

#### **Conexión a la API**

In [2]:
import requests
import json
from pandas import json_normalize

response = requests.get("https://randomuser.me/api/")
print(response.status_code) # 200 ==> Quiere decir que la conexión es satisfactoria

200

#### **Extraer información en el tipo `string`**

In [3]:
print(response.text)
print(type(response.text)) # <class 'str'>

{"results":[{"gender":"female","name":{"title":"Ms","first":"Judith","last":"Schulten"},"location":{"street":{"number":8875,"name":"Schulstraße"},"city":"Auerbach/Vogtl.","state":"Rheinland-Pfalz","country":"Germany","postcode":32286,"coordinates":{"latitude":"-50.2451","longitude":"106.1825"},"timezone":{"offset":"+5:30","description":"Bombay, Calcutta, Madras, New Delhi"}},"email":"judith.schulten@example.com","login":{"uuid":"8cdbed0a-3202-4e73-ab85-1e7abb6985f2","username":"goldenbutterfly923","password":"lucas1","salt":"jci6CnzS","md5":"1ea5653311352639cf8b426bf118a3aa","sha1":"0972712d9d85ed44b43fe2cb29c2961f1c35b4b9","sha256":"ae7f4be761aa08ffd51ed7c972ba35ba8b65fa3b7687af6c52ccbc4923ba0a82"},"dob":{"date":"1970-01-30T09:22:52.296Z","age":54},"registered":{"date":"2014-12-23T03:11:01.107Z","age":9},"phone":"0735-5391561","cell":"0171-9031528","id":{"name":"SVNR","value":"54 300170 S 915"},"picture":{"large":"https://randomuser.me/api/portraits/women/70.jpg","medium":"https://randomuser.me/api/portraits/med/women/70.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/women/70.jpg"},"nat":"DE"}],"info":{"seed":"335b3bc7c4eab1f1","results":1,"page":1,"version":"1.4"}}
<class 'str'>

#### **Extraer información en el tipo `diccionario`**

In [4]:
print(response.json())
print(type(response.json())) # <class 'dict'>

{'results': [{'gender': 'female', 'name': {'title': 'Ms', 'first': 'Judith', 'last': 'Schulten'}, 'location': {'street': {'number': 8875, 'name': 'Schulstraße'}, 'city': 'Auerbach/Vogtl.', 'state': 'Rheinland-Pfalz', 'country': 'Germany', 'postcode': 32286, 'coordinates': {'latitude': '-50.2451', 'longitude': '106.1825'}, 'timezone': {'offset': '+5:30', 'description': 'Bombay, Calcutta, Madras, New Delhi'}}, 'email': 'judith.schulten@example.com', 'login': {'uuid': '8cdbed0a-3202-4e73-ab85-1e7abb6985f2', 'username': 'goldenbutterfly923', 'password': 'lucas1', 'salt': 'jci6CnzS', 'md5': '1ea5653311352639cf8b426bf118a3aa', 'sha1': '0972712d9d85ed44b43fe2cb29c2961f1c35b4b9', 'sha256': 'ae7f4be761aa08ffd51ed7c972ba35ba8b65fa3b7687af6c52ccbc4923ba0a82'}, 'dob': {'date': '1970-01-30T09:22:52.296Z', 'age': 54}, 'registered': {'date': '2014-12-23T03:11:01.107Z', 'age': 9}, 'phone': '0735-5391561', 'cell': '0171-9031528', 'id': {'name': 'SVNR', 'value': '54 300170 S 915'}, 'picture': {'large': 'https://randomuser.me/api/portraits/women/70.jpg', 'medium': 'https://randomuser.me/api/portraits/med/women/70.jpg', 'thumbnail': 'https://randomuser.me/api/portraits/thumb/women/70.jpg'}, 'nat': 'DE'}], 'info': {'seed': '335b3bc7c4eab1f1', 'results': 1, 'page': 1, 'version': '1.4'}}
<class 'dict'>

In [5]:
respuesta = json.loads(response.text)
print(respuesta)
print(type(respuesta)) # <class 'dict'>

{'results': [{'gender': 'female', 'name': {'title': 'Ms', 'first': 'Judith', 'last': 'Schulten'}, 'location': {'street': {'number': 8875, 'name': 'Schulstraße'}, 'city': 'Auerbach/Vogtl.', 'state': 'Rheinland-Pfalz', 'country': 'Germany', 'postcode': 32286, 'coordinates': {'latitude': '-50.2451', 'longitude': '106.1825'}, 'timezone': {'offset': '+5:30', 'description': 'Bombay, Calcutta, Madras, New Delhi'}}, 'email': 'judith.schulten@example.com', 'login': {'uuid': '8cdbed0a-3202-4e73-ab85-1e7abb6985f2', 'username': 'goldenbutterfly923', 'password': 'lucas1', 'salt': 'jci6CnzS', 'md5': '1ea5653311352639cf8b426bf118a3aa', 'sha1': '0972712d9d85ed44b43fe2cb29c2961f1c35b4b9', 'sha256': 'ae7f4be761aa08ffd51ed7c972ba35ba8b65fa3b7687af6c52ccbc4923ba0a82'}, 'dob': {'date': '1970-01-30T09:22:52.296Z', 'age': 54}, 'registered': {'date': '2014-12-23T03:11:01.107Z', 'age': 9}, 'phone': '0735-5391561', 'cell': '0171-9031528', 'id': {'name': 'SVNR', 'value': '54 300170 S 915'}, 'picture': {'large': 'https://randomuser.me/api/portraits/women/70.jpg', 'medium': 'https://randomuser.me/api/portraits/med/women/70.jpg', 'thumbnail': 'https://randomuser.me/api/portraits/thumb/women/70.jpg'}, 'nat': 'DE'}], 'info': {'seed': '335b3bc7c4eab1f1', 'results': 1, 'page': 1, 'version': '1.4'}}
<class 'dict'>

#### **Extraer información de la API**

Utilizamos el diccionario **`respuesta`** creado anteriormente:

In [6]:
from pprint import pprint

pprint(respuesta['results'])
print(type(respuesta['results'])) # <class 'list'>

[{'cell': '0171-9031528',
  'dob': {'age': 54, 'date': '1970-01-30T09:22:52.296Z'},
  'email': 'judith.schulten@example.com',
  'gender': 'female',
  'id': {'name': 'SVNR', 'value': '54 300170 S 915'},
  'location': {'city': 'Auerbach/Vogtl.',
               'coordinates': {'latitude': '-50.2451', 'longitude': '106.1825'},
               'country': 'Germany',
               'postcode': 32286,
               'state': 'Rheinland-Pfalz',
               'street': {'name': 'Schulstraße', 'number': 8875},
               'timezone': {'description': 'Bombay, Calcutta, Madras, New '
                                           'Delhi',
                            'offset': '+5:30'}},
  'login': {'md5': '1ea5653311352639cf8b426bf118a3aa',
            'password': 'lucas1',
            'salt': 'jci6CnzS',
            'sha1': '0972712d9d85ed44b43fe2cb29c2961f1c35b4b9',
            'sha256': 'ae7f4be761aa08ffd51ed7c972ba35ba8b65fa3b7687af6c52ccbc4923ba0a82',
            'username': 'goldenbutterfly923',
            'uuid': '8cdbed0a-3202-4e73-ab85-1e7abb6985f2'},
  'name': {'first': 'Judith', 'last': 'Schulten', 'title': 'Ms'},
  'nat': 'DE',
  'phone': '0735-5391561',
  'picture': {'large': 'https://randomuser.me/api/portraits/women/70.jpg',
              'medium': 'https://randomuser.me/api/portraits/med/women/70.jpg',
              'thumbnail': 'https://randomuser.me/api/portraits/thumb/women/70.jpg'},
  'registered': {'age': 9, 'date': '2014-12-23T03:11:01.107Z'}}]
<class 'list'>

In [7]:
pprint(respuesta['results'][0])
print(type(respuesta['results'][0])) # <class 'dict'>

{'cell': '0171-9031528',
 'dob': {'age': 54, 'date': '1970-01-30T09:22:52.296Z'},
 'email': 'judith.schulten@example.com',
 'gender': 'female',
 'id': {'name': 'SVNR', 'value': '54 300170 S 915'},
 'location': {'city': 'Auerbach/Vogtl.',
              'coordinates': {'latitude': '-50.2451', 'longitude': '106.1825'},
              'country': 'Germany',
              'postcode': 32286,
              'state': 'Rheinland-Pfalz',
              'street': {'name': 'Schulstraße', 'number': 8875},
              'timezone': {'description': 'Bombay, Calcutta, Madras, New Delhi',
                           'offset': '+5:30'}},
 'login': {'md5': '1ea5653311352639cf8b426bf118a3aa',
           'password': 'lucas1',
           'salt': 'jci6CnzS',
           'sha1': '0972712d9d85ed44b43fe2cb29c2961f1c35b4b9',
           'sha256': 'ae7f4be761aa08ffd51ed7c972ba35ba8b65fa3b7687af6c52ccbc4923ba0a82',
           'username': 'goldenbutterfly923',
           'uuid': '8cdbed0a-3202-4e73-ab85-1e7abb6985f2'},
 'name': {'first': 'Judith', 'last': 'Schulten', 'title': 'Ms'},
 'nat': 'DE',
 'phone': '0735-5391561',
 'picture': {'large': 'https://randomuser.me/api/portraits/women/70.jpg',
             'medium': 'https://randomuser.me/api/portraits/med/women/70.jpg',
             'thumbnail': 'https://randomuser.me/api/portraits/thumb/women/70.jpg'},
 'registered': {'age': 9, 'date': '2014-12-23T03:11:01.107Z'}}
<class 'dict'>

#### **Normalizar la data en un Dataframe**

##### **`Forma 1`**

In [8]:
answer = respuesta['results'][0]

df = json_normalize({
    'firstname':answer['name']['first'],
    'lastname':answer['name']['last'],
    'country':answer['location']['country'],
    'username':answer['login']['username'],
    'password':answer['login']['password'],
    'email':answer['email']
})

print(df)
print(type(df)) # <class 'pandas.core.frame.DataFrame'>

  firstname  lastname  country            username password  \
0    Judith  Schulten  Germany  goldenbutterfly923   lucas1

                         email
0  judith.schulten@example.com
<class 'pandas.core.frame.DataFrame'>

In [9]:
display(df)

,firstname,lastname,country,username,password,email
0,Judith,Schulten,Germany,goldenbutterfly923,lucas1,judith.schulten@example.com

##### **`Forma 2`**

In [10]:
import pandas as pd

flattened_data = []
for e in respuesta['results']:
    nat = e.get('nat', pd.NA)
    phone = e.get('phone', pd.NA)
    gender = e.get('gender', pd.NA)
    email = e.get('email', pd.NA)
    cell = e.get('cell', pd.NA) 
    # age = e['dob]['age] <------------- Lo mismo
    age  = e.get('dob', pd.NA)['age']      
    date  = e.get('dob', pd.NA)['date']  
    name  = e.get('id', pd.NA)['name']      
    value  = e.get('id', pd.NA)['value']             
    entry = {
                        'nat': nat,
                        'telefono': phone,
                        'genero': gender,
                        'correo': email,
                        'cell': cell,
                        'edad': age,
                        'fecha': date,
                        'nombre': name,
                        'valor': value,
                        }
    flattened_data.append(entry)
    
    print(flattened_data)
    
df = pd.DataFrame(flattened_data)

[{'nat': 'DE', 'telefono': '0735-5391561', 'genero': 'female', 'correo': 'judith.schulten@example.com', 'cell': '0171-9031528', 'edad': 54, 'fecha': '1970-01-30T09:22:52.296Z', 'nombre': 'SVNR', 'valor': '54 300170 S 915'}]

In [11]:
display(df)

,nat,telefono,genero,correo,cell,edad,fecha,nombre,valor
0,DE,0735-5391561,female,judith.schulten@example.com,0171-9031528,54,1970-01-30T09:22:52.296Z,SVNR,54 300170 S 915

In [13]:
data = respuesta['results'][0]

result = pd.json_normalize(data)
result

,gender,email,phone,cell,nat,name.title,name.first,name.last,location.street.number,location.street.name,...,login.sha256,dob.date,dob.age,registered.date,registered.age,id.name,id.value,picture.large,picture.medium,picture.thumbnail
0,female,judith.schulten@example.com,0735-5391561,0171-9031528,DE,Ms,Judith,Schulten,8875,Schulstraße,...,ae7f4be761aa08ffd51ed7c972ba35ba8b65fa3b7687af...,1970-01-30T09:22:52.296Z,54,2014-12-23T03:11:01.107Z,9,SVNR,54 300170 S 915,https://randomuser.me/api/portraits/women/70.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...