### **Web scrapping utilizando Pandas**

Vamos a scrapear el sitio:

https://www.football-data.co.uk/data.php

### **1 - Leer un archivo `.csv` desde la `URL` con `Pandas`**

#### **Paso a paso: `Temporada 23/24 Premier League`**

Revisamos el sitio el cual scrapearemos y copiamos el link de descarga del archivo CSV con los resultados de la Premier League:

<center><img src="https://i.postimg.cc/x1CWgCgr/dl49.png"></center>

#### **Desarrollo**

In [1]:
import pandas as pd

In [2]:
df_premier24 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/E0.csv')

In [3]:
# showing dataframe
df_premier24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,E0,13/04/2024,17:30,Bournemouth,Man United,2,2,D,2,1,...,3.04,-0.25,2.05,1.75,2.12,1.83,2.16,1.84,2.08,1.79
319,E0,14/04/2024,14:00,Liverpool,Crystal Palace,0,1,A,0,1,...,3.56,-2.00,1.89,2.04,1.87,2.06,1.93,2.06,1.87,2.00
320,E0,14/04/2024,14:00,West Ham,Fulham,0,2,A,0,1,...,2.22,-0.25,2.11,1.82,2.14,1.82,2.14,1.83,2.10,1.79
321,E0,14/04/2024,16:30,Arsenal,Aston Villa,0,2,A,0,0,...,2.87,-1.75,1.95,1.98,1.96,1.96,1.98,2.02,1.91,1.95
322,E0,15/04/2024,20:00,Chelsea,Everton,6,0,H,4,0,...,2.31,-0.75,1.86,2.07,1.86,2.08,1.88,2.09,1.85,2.02

In [4]:
# renombramos las siguientes columnas
df_premier24 = df_premier24.rename(columns={'Date':'fecha',
                                            'HomeTeam':'equipo_local',
                                            'AwayTeam':'equipo_visita',
                                            'FTHG': 'goles_local',
                                            'FTAG': 'goles_visita'})

In [5]:
# El primer parametro corresponde a las filas que necesitemos llamar. En este caso, si es obligatorio colocar : en el primer
# argumento al momento de filtrar columnas:
df_premier24.loc[:, ['fecha', 'equipo_local', 'equipo_visita', 'goles_local', 'goles_visita']]

          fecha equipo_local   equipo_visita  goles_local  goles_visita
0    11/08/2023      Burnley        Man City            0             3
1    12/08/2023      Arsenal   Nott'm Forest            2             1
2    12/08/2023  Bournemouth        West Ham            1             1
3    12/08/2023     Brighton           Luton            4             1
4    12/08/2023      Everton          Fulham            0             1
..          ...          ...             ...          ...           ...
318  13/04/2024  Bournemouth      Man United            2             2
319  14/04/2024    Liverpool  Crystal Palace            0             1
320  14/04/2024     West Ham          Fulham            0             2
321  14/04/2024      Arsenal     Aston Villa            0             2
322  15/04/2024      Chelsea         Everton            6             0

[323 rows x 5 columns]

In [8]:
# Queremos filtrar solo los partidos donde se vea involucrado Manchester City
df_premier24.loc[df_premier24.equipo_local=='Man City', ['fecha', 'equipo_local', 'equipo_visita', 'goles_local', 'goles_visita']]

          fecha equipo_local     equipo_visita  goles_local  goles_visita
15   19/08/2023     Man City         Newcastle            1             0
34   02/09/2023     Man City            Fulham            5             1
51   23/09/2023     Man City     Nott'm Forest            2             0
83   21/10/2023     Man City          Brighton            2             1
104  04/11/2023     Man City       Bournemouth            6             1
120  25/11/2023     Man City         Liverpool            1             1
139  03/12/2023     Man City         Tottenham            3             3
162  16/12/2023     Man City    Crystal Palace            2             2
191  30/12/2023     Man City  Sheffield United            2             0
213  31/01/2024     Man City           Burnley            3             1
228  10/02/2024     Man City           Everton            2             0
244  17/02/2024     Man City           Chelsea            1             1
248  20/02/2024     Man City         Brentford            1             0
266  03/03/2024     Man City        Man United            3             1
292  31/03/2024     Man City           Arsenal            0             0
300  03/04/2024     Man City       Aston Villa            4             1
316  13/04/2024     Man City             Luton            5             1

### **2 - Leer un archivo `.csv` desde múltiples `URLs` con `Pandas`**

#### **Paso a paso: `Temporada 23/24 para 3 ligas de Inglaterra -> Premier League, Championship y Liga 1`**

Revisamos el sitio el cual scrapearemos y veemos que existen varios links de descarga de archivos CSV con los resultados de las distintas ligas de fútbol de Inglaterra:

<center><img src="https://i.postimg.cc/MHyJVFW9/dl50.png"></center>

#### **Desarrollo**

In [14]:
import pandas as pd

**Link: base + temporada + liga**

In [9]:
# Estructura del link
"https://www.football-data.co.uk/mmz4281/" + "2324" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2324/E0.csv'

In [11]:
# crear una base variable
base = "https://www.football-data.co.uk/mmz4281/"

**Multiples ligas**

- https://www.football-data.co.uk/mmz4281/2324/E0.csv
- https://www.football-data.co.uk/mmz4281/2324/E1.csv
- https://www.football-data.co.uk/mmz4281/2324/E2.csv
- https://www.football-data.co.uk/mmz4281/2324/E3.csv
- https://www.football-data.co.uk/mmz4281/2324/EC.csv

##### **Código**

In [24]:
# crear lista de ligas
ligas = ['E0','E1', 'E2']

lista_df = []
# looping a través de ligas, leer múltiples csv y anexarlos en una lista
for liga in ligas:
    df = pd.read_csv(base + "2324" + "/"  + liga + ".csv")
    lista_df.append(df)

In [25]:
# lista de dataframes
len(lista_df)

3

In [26]:
lista_df[0].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88

In [27]:
lista_df[1].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,04/08/2023,20:00,Sheffield Weds,Southampton,1,2,A,0,1,...,1.83,0.25,1.91,1.99,1.93,2.00,1.97,2.00,1.88,1.95
1,E1,05/08/2023,15:00,Blackburn,West Brom,2,1,H,2,0,...,1.70,0.00,2.05,1.85,2.07,1.85,2.10,1.88,2.03,1.82
2,E1,05/08/2023,15:00,Bristol City,Preston,1,1,D,0,0,...,1.68,-0.25,1.82,2.08,1.84,2.08,1.88,2.15,1.80,2.04
3,E1,05/08/2023,15:00,Middlesbrough,Millwall,0,1,A,0,0,...,1.77,-0.25,1.80,2.10,1.83,2.10,1.91,2.14,1.85,1.99
4,E1,05/08/2023,15:00,Norwich,Hull,2,1,H,1,1,...,1.92,-0.75,2.06,1.84,2.05,1.86,2.10,1.91,2.01,1.83

In [28]:
lista_df[2].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,05/08/2023,15:00,Barnsley,Port Vale,7,0,H,2,0,...,1.75,-0.75,2.03,1.83,2.07,1.83,2.09,1.85,2.01,1.80
1,E2,05/08/2023,15:00,Blackpool,Burton,2,0,H,2,0,...,2.10,-0.75,1.93,1.93,1.94,1.94,1.96,1.97,1.88,1.91
2,E2,05/08/2023,15:00,Bolton,Lincoln,3,0,H,1,0,...,1.67,-0.75,2.00,1.85,2.01,1.88,2.02,1.92,1.96,1.84
3,E2,05/08/2023,15:00,Cambridge,Oxford,2,0,H,2,0,...,1.71,0.25,1.93,1.93,1.95,1.93,2.00,1.98,1.90,1.90
4,E2,05/08/2023,15:00,Carlisle,Fleetwood Town,1,1,D,1,1,...,1.62,-0.25,2.00,1.85,2.07,1.83,2.08,1.90,2.00,1.80

#### **Paso a paso: `Múltiples temporadas para 3 ligas de Inglaterra -> Premier League, Championship y Liga 1`**

Revisamos el sitio el cual scrapearemos y veemos que existen varios links de descarga de archivos CSV con los resultados de las distintas ligas de fútbol de Inglaterra:

<center><img src="https://i.postimg.cc/MHyJVFW9/dl50.png"></center>

#### **Desarrollo**

In [1]:
import pandas as pd
import numpy as np

**Link: base + temporada + liga**

In [2]:
# Estructura del link
"https://www.football-data.co.uk/mmz4281/" + "2324" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2324/E0.csv'

In [3]:
# crear una base variable
base = "https://www.football-data.co.uk/mmz4281/"
base

'https://www.football-data.co.uk/mmz4281/'

##### **Código**

In [4]:
ligas = ['E0','E1','E2']

lista_df = []

# recorre el rango de temporadas e inserta una nueva columna
for liga in ligas:
    for temporada in range(19,24): # rango de temporadas
        df = pd.read_csv(base + str(temporada) + str(temporada+1) + "/" + liga + ".csv")
        df.insert(1, 'temporada', str(temporada)+"/"+str(temporada+1))
        lista_df.append(df)

In [5]:
# dataframes totales (5 temporadas x 3 ligas)
len(lista_df)

15

In [6]:
# Vamos a concantenar las temporadas 19/20, 20/21, 21/22, 22/23 y 23/24 de la Premier League
df_premier_league = pd.concat(lista_df[0:5])
df_premier_league

,Div,temporada,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,19/20,09/08/2019,20:00,Liverpool,Norwich,4,1,H,4,...,3.43,-2.25,1.91,1.99,1.94,1.98,1.99,2.07,1.90,1.99
1,E0,19/20,10/08/2019,12:30,West Ham,Man City,0,5,A,0,...,2.91,1.75,1.95,1.95,1.96,1.97,2.07,1.98,1.97,1.92
2,E0,19/20,10/08/2019,15:00,Bournemouth,Sheffield United,1,1,D,0,...,1.92,-0.50,1.95,1.95,1.98,1.95,2.00,1.96,1.96,1.92
3,E0,19/20,10/08/2019,15:00,Burnley,Southampton,3,0,H,0,...,1.71,0.00,1.87,2.03,1.89,2.03,1.90,2.07,1.86,2.02
4,E0,19/20,10/08/2019,15:00,Crystal Palace,Everton,0,0,D,0,...,1.71,0.25,1.82,2.08,1.97,1.96,2.03,2.08,1.96,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,E0,23/24,13/04/2024,17:30,Bournemouth,Man United,2,2,D,2,...,3.04,-0.25,2.05,1.75,2.12,1.83,2.16,1.84,2.08,1.79
319,E0,23/24,14/04/2024,14:00,Liverpool,Crystal Palace,0,1,A,0,...,3.56,-2.00,1.89,2.04,1.87,2.06,1.93,2.06,1.87,2.00
320,E0,23/24,14/04/2024,14:00,West Ham,Fulham,0,2,A,0,...,2.22,-0.25,2.11,1.82,2.14,1.82,2.14,1.83,2.10,1.79
321,E0,23/24,14/04/2024,16:30,Arsenal,Aston Villa,0,2,A,0,...,2.87,-1.75,1.95,1.98,1.96,1.96,1.98,2.02,1.91,1.95
322,E0,23/24,15/04/2024,20:00,Chelsea,Everton,6,0,H,4,...,2.31,-0.75,1.86,2.07,1.86,2.08,1.88,2.09,1.85,2.02

In [7]:
# renombramos las siguientes columnas
df_premier_league = df_premier_league.rename(columns={'Date':'fecha',
                                                      'HomeTeam':'equipo_local',
                                                      'AwayTeam':'equipo_visita',
                                                      'FTHG': 'goles_local',
                                                      'FTAG': 'goles_visita',
                                                      'FTR': 'resultado'})

In [31]:
# Queremos filtrar solo los partidos donde se vea involucrado Manchester City
df_man_city = df_premier_league.loc[df_premier_league.equipo_local=='Man City', ['temporada', 'fecha', 'equipo_local', 'equipo_visita', 'goles_local', 'goles_visita', 'resultado']]
df_man_city

,temporada,fecha,equipo_local,equipo_visita,goles_local,goles_visita,resultado
16,19/20,17/08/2019,Man City,Tottenham,2,2,D
34,19/20,31/08/2019,Man City,Brighton,4,0,H
54,19/20,21/09/2019,Man City,Watford,8,0,H
77,19/20,06/10/2019,Man City,Wolves,0,2,A
91,19/20,26/10/2019,Man City,Aston Villa,3,0,H
...,...,...,...,...,...,...,...
248,23/24,20/02/2024,Man City,Brentford,1,0,H
266,23/24,03/03/2024,Man City,Man United,3,1,H
292,23/24,31/03/2024,Man City,Arsenal,0,0,D
300,23/24,03/04/2024,Man City,Aston Villa,4,1,H
316,23/24,13/04/2024,Man City,Luton,5,1,H

In [32]:
len(df_man_city)

93

In [33]:
# generar una nueva columna con numeros escalares ordenados
indice_= np.arange(0,93)
indice_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92])

In [34]:
df_man_city['indice'] = indice_
df_man_city

,temporada,fecha,equipo_local,equipo_visita,goles_local,goles_visita,resultado,indice
16,19/20,17/08/2019,Man City,Tottenham,2,2,D,0
34,19/20,31/08/2019,Man City,Brighton,4,0,H,1
54,19/20,21/09/2019,Man City,Watford,8,0,H,2
77,19/20,06/10/2019,Man City,Wolves,0,2,A,3
91,19/20,26/10/2019,Man City,Aston Villa,3,0,H,4
...,...,...,...,...,...,...,...,...
248,23/24,20/02/2024,Man City,Brentford,1,0,H,88
266,23/24,03/03/2024,Man City,Man United,3,1,H,89
292,23/24,31/03/2024,Man City,Arsenal,0,0,D,90
300,23/24,03/04/2024,Man City,Aston Villa,4,1,H,91
316,23/24,13/04/2024,Man City,Luton,5,1,H,92

In [35]:
# establecer columna indice como índice y actualizamos el Dataframe
df_man_city.set_index('indice', inplace=True)
df_man_city

,temporada,fecha,equipo_local,equipo_visita,goles_local,goles_visita,resultado
indice,,,,,,,
0,19/20,17/08/2019,Man City,Tottenham,2,2,D
1,19/20,31/08/2019,Man City,Brighton,4,0,H
2,19/20,21/09/2019,Man City,Watford,8,0,H
3,19/20,06/10/2019,Man City,Wolves,0,2,A
4,19/20,26/10/2019,Man City,Aston Villa,3,0,H
...,...,...,...,...,...,...,...
88,23/24,20/02/2024,Man City,Brentford,1,0,H
89,23/24,03/03/2024,Man City,Man United,3,1,H
90,23/24,31/03/2024,Man City,Arsenal,0,0,D
91,23/24,03/04/2024,Man City,Aston Villa,4,1,H
92,23/24,13/04/2024,Man City,Luton,5,1,H

----
Un pequeño testeo:

In [13]:
def funcion(elemento):
    if elemento == 'D':
        return 'E'

lista = ['A','B','C','D','E']

x = list(map(funcion, lista))
print(x)

[None, None, None, 'E', None]

----

Modificamos los valores de la columna "resultado":

In [36]:
def funcion(elemento):
    if elemento == 'D':
        return 'E'
    elif elemento == 'H':
        return 'L'
    else:
        return 'V'
    
resultado = list(df_man_city.resultado)
nuevo_resultado = list(map(funcion, resultado))
nuevo_resultado

['E',
 'L',
 'L',
 'V',
 'L',
 'L',
 'L',
 'V',
 'L',
 'L',
 'L',
 'E',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'V',
 'L',
 'E',
 'L',
 'L',
 'E',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'V',
 'L',
 'V',
 'V',
 'L',
 'L',
 'L',
 'E',
 'L',
 'V',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'V',
 'L',
 'E',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'V',
 'E',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'L',
 'E',
 'E',
 'E',
 'L',
 'L',
 'L',
 'E',
 'L',
 'L',
 'E',
 'L',
 'L']

In [37]:
df_man_city['resultado'] = nuevo_resultado
df_man_city

,temporada,fecha,equipo_local,equipo_visita,goles_local,goles_visita,resultado
indice,,,,,,,
0,19/20,17/08/2019,Man City,Tottenham,2,2,E
1,19/20,31/08/2019,Man City,Brighton,4,0,L
2,19/20,21/09/2019,Man City,Watford,8,0,L
3,19/20,06/10/2019,Man City,Wolves,0,2,V
4,19/20,26/10/2019,Man City,Aston Villa,3,0,L
...,...,...,...,...,...,...,...
88,23/24,20/02/2024,Man City,Brentford,1,0,L
89,23/24,03/03/2024,Man City,Man United,3,1,L
90,23/24,31/03/2024,Man City,Arsenal,0,0,E
91,23/24,03/04/2024,Man City,Aston Villa,4,1,L
92,23/24,13/04/2024,Man City,Luton,5,1,L

#### **Paso a paso: `Múltiples temporadas para La Liga (España), Bundesliga (Alemania) y la Premier League (Inglaterra)`**

#### **Desarrollo**

In [25]:
import pandas as pd

**Link: base + temporada + liga**

In [26]:
# Estructura del link
"https://www.football-data.co.uk/mmz4281/" + "2324" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2324/E0.csv'

In [27]:
# crear una base variable
base = "https://www.football-data.co.uk/mmz4281/"
base

'https://www.football-data.co.uk/mmz4281/'

In [28]:
# crear un diccionario con el nombre original de la liga como key
dict_paises = {'La Liga':'SP1',
               'Bundesliga':'D1', 
               'Premier League':'E0',
              }

In [29]:
# obtener un elemento del diccionario
dict_paises['La Liga']

'SP1'

In [30]:
for liga in dict_paises:
    print(liga)

La Liga
Bundesliga
Premier League

##### **Código**

In [31]:
dict_historical_data = {} 

# looping through key elements
for liga in dict_paises:
    lista_df = [] # one dataframe per league
    for temporada in range(19, 24):
        df = pd.read_csv(base + str(temporada) + str(temporada+1) + "/" + dict_paises[liga]+ ".csv")
        df.insert(1, 'temporada', str(temporada)+"/"+str(temporada+1))
        lista_df.append(df)
    df_frames = pd.concat(lista_df) # almacenar todas las temporadas de una liga en un único dataframe
    dict_historical_data[liga] = df_frames  # asignar dataframe a un nuevo diccionario

In [32]:
 # mostrar dataframe dentro de dict_historical_data
dict_historical_data['La Liga']

,Div,temporada,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,19/20,16/08/2019,20:00,Ath Bilbao,Barcelona,1,0,H,0,...,1.97,0.75,1.93,2.00,1.91,2.01,2.02,2.03,1.91,1.98
1,SP1,19/20,17/08/2019,16:00,Celta,Real Madrid,1,3,A,0,...,2.63,1.00,1.82,1.97,1.85,2.07,2.00,2.20,1.82,2.06
2,SP1,19/20,17/08/2019,18:00,Valencia,Sociedad,1,1,D,0,...,1.82,-0.75,1.94,1.99,1.92,2.00,1.96,2.12,1.89,2.00
3,SP1,19/20,17/08/2019,19:00,Mallorca,Eibar,2,1,H,1,...,1.66,0.00,2.11,1.82,2.09,1.83,2.12,1.88,2.07,1.83
4,SP1,19/20,17/08/2019,20:00,Leganes,Osasuna,0,1,A,0,...,1.46,-0.50,1.89,2.04,1.90,2.01,1.95,2.06,1.90,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,SP1,23/24,14/04/2024,13:00,Las Palmas,Sevilla,0,2,A,0,...,1.81,0.00,1.99,1.94,1.99,1.93,2.02,1.96,1.98,1.89
306,SP1,23/24,14/04/2024,15:15,Granada,Alaves,2,0,H,2,...,1.59,0.00,1.85,2.08,1.86,2.08,1.91,2.09,1.86,2.01
307,SP1,23/24,14/04/2024,17:30,Ath Bilbao,Villarreal,1,1,D,0,...,2.23,-1.00,2.06,1.87,2.05,1.88,2.11,1.89,2.01,1.85
308,SP1,23/24,14/04/2024,20:00,Sociedad,Almeria,2,2,D,1,...,2.20,-1.50,1.93,2.00,1.93,1.98,1.99,2.01,1.91,1.94
309,SP1,23/24,15/04/2024,20:00,Osasuna,Valencia,0,1,A,0,...,1.49,-0.25,2.04,1.86,2.06,1.88,2.08,1.89,2.01,1.84